version: "3"

services:
  victoriametrics:
    image: victoriametrics/victoria-metrics
    ports:
      - "8428:8428"
    command:
      - "--storageDataPath=/storage"
    volumes:
      - vmdata:/storage

  vmagent:
    image: victoriametrics/vmagent
    depends_on:
      - victoriametrics
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "-promscrape.config=/etc/prometheus/prometheus.yml"
      - "-remoteWrite.url=http://victoriametrics:8428/api/v1/write"

  node-exporter:
    image: prom/node-exporter
    ports:
      - "9100:9100"

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"

volumes:
  vmdata:
